package unit05_mysql.sample;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Boards implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 글 아이디. */
	private Integer bid;

	/** 사용자. */
	private Users busers;

	/** 제목. */
	private String title;

	/** 내용. */
	private String content;

	/** 수정일시. */
	private Date modtime;

	/** 조회수. */
	private Integer viewcount;

	/** 댓글수. */
	private Integer replycount;

	/** isDeleted. */
	private Integer isdeleted;

	/** 댓글 목록. */
	private Set<Replies> repliesSet;

	/**
	 * 생성자.
	 */
	public Boards() {
		this.repliesSet = new HashSet<Replies>();
	}

	/**
	 * 글 아이디을 설정합니다..
	 * 
	 * @param bid
	 *            글 아이디
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * 글 아이디을 가져옵니다..
	 * 
	 * @return 글 아이디
	 */
	public Integer getBid() {
		return this.bid;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param busers
	 *            사용자
	 */
	public void setBusers(Users busers) {
		this.busers = busers;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getBusers() {
		return this.busers;
	}

	/**
	 * 제목을 설정합니다..
	 * 
	 * @param title
	 *            제목
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * 제목을 가져옵니다..
	 * 
	 * @return 제목
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param content
	 *            내용
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * 수정일시을 설정합니다..
	 * 
	 * @param modtime
	 *            수정일시
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

	/**
	 * 수정일시을 가져옵니다..
	 * 
	 * @return 수정일시
	 */
	public Date getModtime() {
		return this.modtime;
	}

	/**
	 * 조회수을 설정합니다..
	 * 
	 * @param viewcount
	 *            조회수
	 */
	public void setViewcount(Integer viewcount) {
		this.viewcount = viewcount;
	}

	/**
	 * 조회수을 가져옵니다..
	 * 
	 * @return 조회수
	 */
	public Integer getViewcount() {
		return this.viewcount;
	}

	/**
	 * 댓글수을 설정합니다..
	 * 
	 * @param replycount
	 *            댓글수
	 */
	public void setReplycount(Integer replycount) {
		this.replycount = replycount;
	}

	/**
	 * 댓글수을 가져옵니다..
	 * 
	 * @return 댓글수
	 */
	public Integer getReplycount() {
		return this.replycount;
	}

	/**
	 * isDeleted을 설정합니다..
	 * 
	 * @param isdeleted
	 *            isDeleted
	 */
	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * isDeleted을 가져옵니다..
	 * 
	 * @return isDeleted
	 */
	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	/**
	 * 댓글 목록을 설정합니다..
	 * 
	 * @param repliesSet
	 *            댓글 목록
	 */
	public void setRepliesSet(Set<Replies> repliesSet) {
		this.repliesSet = repliesSet;
	}

	/**
	 * 댓글를 추가합니다..
	 * 
	 * @param replies
	 *            댓글
	 */
	public void addReplies(Replies replies) {
		this.repliesSet.add(replies);
	}

	/**
	 * 댓글 목록을 가져옵니다..
	 * 
	 * @return 댓글 목록
	 */
	public Set<Replies> getRepliesSet() {
		return this.repliesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bid == null) ? 0 : bid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Boards other = (Boards) obj;
		if (bid == null) {
			if (other.bid != null) {
				return false;
			}
		} else if (!bid.equals(other.bid)) {
			return false;
		}
		return true;
	}

}
