package unit05_mysql.sample;

import java.io.Serializable;
import java.util.Date;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Replies implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글 아이디. */
	private Integer rid;

	/** 게시판. */
	private Boards rboards;

	/** 사용자. */
	private Users rusers;

	/** 내용. */
	private String content;

	/** 작성일시. */
	private Date regtime;

	/**
	 * 생성자.
	 */
	public Replies() {
	}

	/**
	 * 댓글 아이디을 설정합니다..
	 * 
	 * @param rid
	 *            댓글 아이디
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * 댓글 아이디을 가져옵니다..
	 * 
	 * @return 댓글 아이디
	 */
	public Integer getRid() {
		return this.rid;
	}

	/**
	 * 게시판을 설정합니다..
	 * 
	 * @param rboards
	 *            게시판
	 */
	public void setRboards(Boards rboards) {
		this.rboards = rboards;
	}

	/**
	 * 게시판을 가져옵니다..
	 * 
	 * @return 게시판
	 */
	public Boards getRboards() {
		return this.rboards;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param rusers
	 *            사용자
	 */
	public void setRusers(Users rusers) {
		this.rusers = rusers;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getRusers() {
		return this.rusers;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param content
	 *            내용
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * 작성일시을 설정합니다..
	 * 
	 * @param regtime
	 *            작성일시
	 */
	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	/**
	 * 작성일시을 가져옵니다..
	 * 
	 * @return 작성일시
	 */
	public Date getRegtime() {
		return this.regtime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rid == null) ? 0 : rid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Replies other = (Replies) obj;
		if (rid == null) {
			if (other.rid != null) {
				return false;
			}
		} else if (!rid.equals(other.rid)) {
			return false;
		}
		return true;
	}

}
