package unit05_mysql.sample;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 저자 아이디. */
	private String uid;

	/** 이름. */
	private String uname;

	/** email. */
	private String email;

	/** 가입일자. */
	private Date regdate;

	/** isDeleted. */
	private Integer isdeleted;

	/** 게시판 목록. */
	private Set<Boards> boardsSet;

	/** 댓글 목록. */
	private Set<Replies> repliesSet;

	/**
	 * 생성자.
	 */
	public Users() {
		this.boardsSet = new HashSet<Boards>();
		this.repliesSet = new HashSet<Replies>();
	}

	/**
	 * 저자 아이디을 설정합니다..
	 * 
	 * @param uid
	 *            저자 아이디
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * 저자 아이디을 가져옵니다..
	 * 
	 * @return 저자 아이디
	 */
	public String getUid() {
		return this.uid;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param uname
	 *            이름
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getUname() {
		return this.uname;
	}

	/**
	 * email을 설정합니다..
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email을 가져옵니다..
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 가입일자을 설정합니다..
	 * 
	 * @param regdate
	 *            가입일자
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * 가입일자을 가져옵니다..
	 * 
	 * @return 가입일자
	 */
	public Date getRegdate() {
		return this.regdate;
	}

	/**
	 * isDeleted을 설정합니다..
	 * 
	 * @param isdeleted
	 *            isDeleted
	 */
	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * isDeleted을 가져옵니다..
	 * 
	 * @return isDeleted
	 */
	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	/**
	 * 게시판 목록을 설정합니다..
	 * 
	 * @param boardsSet
	 *            게시판 목록
	 */
	public void setBoardsSet(Set<Boards> boardsSet) {
		this.boardsSet = boardsSet;
	}

	/**
	 * 게시판를 추가합니다..
	 * 
	 * @param boards
	 *            게시판
	 */
	public void addBoards(Boards boards) {
		this.boardsSet.add(boards);
	}

	/**
	 * 게시판 목록을 가져옵니다..
	 * 
	 * @return 게시판 목록
	 */
	public Set<Boards> getBoardsSet() {
		return this.boardsSet;
	}

	/**
	 * 댓글 목록을 설정합니다..
	 * 
	 * @param repliesSet
	 *            댓글 목록
	 */
	public void setRepliesSet(Set<Replies> repliesSet) {
		this.repliesSet = repliesSet;
	}

	/**
	 * 댓글를 추가합니다..
	 * 
	 * @param replies
	 *            댓글
	 */
	public void addReplies(Replies replies) {
		this.repliesSet.add(replies);
	}

	/**
	 * 댓글 목록을 가져옵니다..
	 * 
	 * @return 댓글 목록
	 */
	public Set<Replies> getRepliesSet() {
		return this.repliesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (uid == null) {
			if (other.uid != null) {
				return false;
			}
		} else if (!uid.equals(other.uid)) {
			return false;
		}
		return true;
	}

}
